version: '3.2'
services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./code
        target: /var/www/html
      - type: bind
        source: ./mysql
        target: /var/lib/mysql
    stdin_open: true
    tty: true